name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: linter
        uses: golangci/golangci-lint-action@v3.2.0

      - name: test
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.19
          stable: true
          run: go test --race -v --benchmem ./...
